version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: slack
  web:
    image: node-express-redis-postgres:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["npm", "start"]
networks:
  webnet:
